# Basic HAPI FHIR configuration
spring.datasource.url=jdbc:postgresql://db:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=apppassword
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hapi.fhir.bulk_export_enabled=true
